### ISSUE TITLE
Refactor views

### ISSUE THREAD

**Issue by TheNeikos** [TheNeikos/the_wyvern_rocks#7]
Bootstrap is awesome! It has lots of redundant html structures though, we can surely extract those to helpers to make things nicer?

This blog post is on point on what I plan to do: 

https://www.igvita.com/2007/03/15/block-helpers-and-dry-views-in-rails/

**Comment by RaceFPV** [comment]
This seems like a more up to date way to do the same thing, yes?

http://stackoverflow.com/a/27367024

**Comment by TheNeikos** [comment]
It seems to do a function call less, so yes pretty much, something like that.
